input {
  tcp {
    port => 5000
    codec => json {
      target => "log"
    }
  }
}

filter {
  if [level] == "ERROR" {
    mutate { add_tag => ["error"] }
  }

  if [level] == "WARN" {
    mutate { add_tag => ["warning"] }
  }

  mutate {
    remove_field => ["@version", "port"]
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]

    data_stream => true
    data_stream_type => "logs"
    data_stream_dataset => "projet7-logs"
    data_stream_namespace => "default"
  }

  stdout { codec => rubydebug }
}